#!/usr/bin/env python

import re
import subprocess as sp

import dominate
import pymongo
from dominate.tags import body, caption, link, table, tbody, td, th, tr
from dominate.util import raw


def green(x):
    return '<span style="color: green;">{}</span>'.format(x)

def red(x):
    return '<span style="color: red;">{}</span>'.format(x)

def orange(x):
    return '<span style="color: orange;">{}</span>'.format(x)

def passed():
    return green('&#10004;')

def failed():
    return red('&#10060;')

def almost():
    return orange('&#9898;')

# pylint: disable=C0103
client = pymongo.MongoClient('mongodb://localhost:27017')
database = client.get_database('card-analysis')

commands = database.commands

ATTACK_NAME = 'BasicTransaction'
doc = dominate.document(title=ATTACK_NAME + ' attack')
with doc.head:
    link(rel='stylesheet', href='../../../tables/stylesheet.css')

body = doc.add(body())
table = body.add(table())
tbody = table.add(tbody())


# stages = commands.find({'attack-id': last_attack_id})
CARD_NAME = 'card-name'
INSTALL = 'installation'
PREPARE1 = 'send INS_PREPARE1'
PREPARE2 = 'send INS_PREPARE2'
READMEM_0000 = 'send INS_READMEM at 0000'
READMEM_0020 = 'send INS_READMEM at 0020'
READMEM_3017 = 'send INS_READMEM at 3017'
READMEM_3201 = 'send INS_READMEM at 3201'
READMEM_4000 = 'send INS_READMEM at 4000'
READMEM_5000 = 'send INS_READMEM at 5000'
UNINSTALL = 'uninstallation'

columns = [
    CARD_NAME,
    INSTALL,
    PREPARE1,
    PREPARE2,
    READMEM_0000,
    READMEM_0020,
    READMEM_3017,
    READMEM_3201,
    READMEM_4000,
    READMEM_5000,
    UNINSTALL
]

def get_install_result(obj):
    if obj['returncode'] == 0:
        return raw(passed())
    last_two = obj['stderr'].strip().split('\n')[-2:]
    return raw(failed() + '</br>' + '</br>'.join(last_two))

def get_uninstall_result(obj):
    if obj['returncode'] == 0:
        return raw(passed())
    last_two = obj['stderr'].strip().split('\n')[-2:]
    return raw(failed() + '</br>' + '</br>'.join(last_two))

def get_read_result(obj):
    # rex = re.compile(r'(A>>.*A0B00000 00.*\nA<<\s*\(.*\)\s+(.*))', re.MULTILINE)
    # read one line after the INS_READ is sent
    rex = re.compile(r'(A>>.*80.* 00.*\n(.*))', re.MULTILINE)
    output = rex.search(obj['stdout'])
    if output:
        out = output.group(2)
        # out = out.replace('\n', '</br>')
        error_code = re.search(r'[A-Z0-9]{4}$', out).group()
        if error_code == '9000':
            if obj['returncode'] == 0:
                ret = passed() + '</br>' + out
            else:
                ret = failed() + '</br>' + out
        else:
            try:
                x = sp.check_output(['jcer', error_code]).decode('utf8').strip()
                err_desc = x.split('\n')[-1]
                ret = '</br>'.join([almost(), error_code, err_desc])
            except sp.CalledProcessError:
                ret = out.strip('<')
        return raw(ret)
    return raw(failed())

with tbody:
    caption = caption(ATTACK_NAME)
    header_row = tr()
    for stage in columns:
        header_row += th(stage)
    for card_name in 'ABCDEFGHI':
        desc = {
            'card-name': card_name,
            'attack-name': ATTACK_NAME,
        }

        last_attack_id = commands.find_one(
            filter=desc,
            sort=[('timestamp', pymongo.DESCENDING)]
        )['attack-id']

        row = tr()
        for stage in columns:
            if stage == CARD_NAME:
                row += td(card_name)
            elif stage == INSTALL:
                obj = commands.find_one({
                    'card-name': card_name,
                    'attack-id':last_attack_id,
                    'stage': INSTALL,
                })
                if obj is None:
                    continue
                row += td(get_install_result(obj))
            elif stage == UNINSTALL:
                obj = commands.find_one({
                    'card-name': card_name,
                    'attack-id':last_attack_id,
                    'stage': UNINSTALL,
                })
                row += td(get_uninstall_result(obj))
            else:
                obj = commands.find_one({
                    'card-name': card_name,
                    'attack-id':last_attack_id,
                    'stage': stage,
                })
                row += td(get_read_result(obj))

print(doc.render())
