#!/usr/bin/env python

import re

from dominate.util import raw

from jcvmutils.tables import Table, failed, passed

ATTACK_NAME = 'ArrayMetadataManipulation'

PATCH = 'send INS_PATCH'


def get_read_result(obj):
    # rex = re.compile(r'(A>>.*A0B00000 00.*\nA<<\s*\(.*\)\s+(.*))', re.MULTILINE)
    # read one line after the INS_READ is sent
    rex = re.compile(r'(A>>.*A0B00000 00.*\n.*)', re.MULTILINE)
    output = rex.search(obj['stdout'])
    if output:
        out = output.group()
        out = out.replace('\n', '</br>')
        if obj['returncode'] == 0:
            ret = passed() + '</br>' + out
        else:
            ret = failed() + '</br>' + out
        return raw(ret)
    return raw(failed())


class Result(Table):
    ATTACK_NAME = 'ArrayMetadataManipulation'
    STAGES = {
        PATCH: get_read_result,
    }

if __name__ == '__main__':
    res = Result()
    print(res.run())
